### ISSUE TITLE
creating very long memos (>16MB) will crash the server

### ISSUE THREAD

**Issue by fluxionary** [BlockySurvival/memorandum#2]
this was brought up in this discussion: https://github.com/minetest/minetest/issues/13365. 

i may create a PR but i've got to evaluate how i want to do that. this mod is ancient and uses deprecated API.

**Comment by fluxionary** [comment]
hm. maybe? i can't seem to post 4096 or more characters at once into a form (nothing happens), posting 2048 characters for a couple minutes seems to have lagged out the client. maybe this is only practically possible w/ a hacked client, but still technically a problem.

**Comment by luk3yx** [comment]
I can paste at least 1MiB of text in (500KB at a time), though my framerate drops significantly when I do.

**Comment by fluxionary** [comment]
i'm using  very recent dev client, it's been completely unresponsive about 20 minutes now. i'll try to verify the actual problem tomorrow by directly writing metadata and not trying to paste stuff into the formspec.

**Comment by fluxionary** [comment]
steps to reproduce:
1. place a piece of paper, and write "test" in it
2. mark the area w/ worldedit
3. run the following script
```lua
local s1 = {}
for _ = 1, 1024 do table.insert(s1, "a") end
local s2 = table.concat(s1, "")
local l1 = {}
for _ = 1, 16*1024 do table.insert(l1, s2) end
local large = table.concat(l1, "")

local meta = minetest.get_meta(worldedit.pos1.flux)
meta:set_string("text", large)
```
4. break the letter

result:
```
2023-03-28 08:29:36: ERROR[ConnectionSend]: In thread 7f431e73a6c0:
2023-03-28 08:29:36: ERROR[ConnectionSend]: /build/minetest/src/minetest-5.6.1/src/network/connection.cpp:413: bool con::UDPPeer::processReliableSendCommand(con::ConnectionCommandPtr&, unsigned int): An engine assumption 'c.data.getSize() < 0x8000*512' failed.
```

probably alternately, you could use a hacked client to directly submit a formspec w/out having to actually bother w/ pasting things in to an actual form.
